### ISSUE TITLE
Fix `HexDebug` trait for `BlsScalar`s

### ISSUE THREAD

**Issue by moCello** [dusk-network/bls12_381#70]
**Describe what you want implemented** 
Currently when we want to print a `BlsScalar` we print the reduced value of the scalar using the `dusk_bytes::HexDebug` trait.
E.g. for a `BlsScalar::from(0x2b5)` the internal representation of that scalar is 
```
BlsScalar([
    0x000005f9fffffa06,
    0x8499c61209ce2dfa,
    0xd84adff66ebaf029,
    0x25a5f8f948c13e7d,
]),
```
Which is the value `0x2b5` in Montgomery form in small endian. When we use the `HexDebug` trait, we first reduce the scalar to its initial value and then print it also in little endian. So for
```
fn main() {
    let scalar = BlsScalar::from(0x2b5);
    println!("{:?}, scalar");
}
```
the output would be
```
b502000000000000000000000000000000000000000000000000000000000000
```
I think for simply displaying a scalar, we should print the value but then in big endian, `00000000000000000000000000000000000000000000000000000000000002b5`

**Describe "Why" this is needed**
Sometimes it is very valuable to see the actual value of a `BlsScalar`

**Describe alternatives you've considered**
na

**Additional context**
na

**Comment by ZER0** [comment]
As discussed, `HexDebug` provides the hexadecimal representation of the bytes format (`to_bytes`) used to test if the right data is sent across wires (gRPC, etc) therefore is make any assumption about the endianness: it's the implementation of `to_bytes` that decide that.

So we can either change the implementation of `to_bytes` to return the bytes in big endian, or we can use `Hex` trait instead of `HexDebug` and add a manual implementation for `Debug` in the format we like.

I would probably opted for the second, because in all our implementation of `to_bytes` we're usually little endian, but let's hear your opinion here too.

**Comment by moCello** [comment]
This is done because the merge with upstream #117 implements Debug printing in big endian
